FROM node:18.13.0-alpine as build

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm install
RUN npm run prod

FROM node:18.13.0-alpine
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/out/  /usr/src/app
RUN npm install -g live-server@1.2.2
CMD ["live-server"]
EXPOSE 80